# Generated by Django 3.0.7 on 2020-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheif', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('recipieName', models.CharField(max_length=20)),
                ('recipie', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MYrecipie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pics')),
                ('recipieName', models.CharField(max_length=20)),
                ('recipie', models.CharField(max_length=500)),
                ('contributedBY', models.CharField(max_length=20)),
                ('likes', models.IntegerField(default='')),
            ],
        ),
    ]
