# Generated by Django 3.0.7 on 2020-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayushi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='recipie',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='myrecipie',
            name='recipie',
            field=models.TextField(max_length=500),
        ),
    ]
