# Generated by Django 3.0.7 on 2020-08-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aayushi', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_set', to='aayushi.MYrecipie'),
        ),
    ]
