# Generated by Django 3.0.7 on 2020-08-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayushi', '0005_auto_20200804_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrecipie',
            name='link',
            field=models.URLField(default='', max_length=100),
        ),
    ]
