# Generated by Django 3.0.7 on 2020-08-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayushi', '0006_myrecipie_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrecipie',
            name='link',
            field=models.URLField(default=' ', max_length=100),
        ),
    ]
