# Generated by Django 3.0.7 on 2020-08-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aayushi', '0007_auto_20200805_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrecipie',
            name='contributedBY',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='myrecipie',
            name='link',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
